### ISSUE TITLE
Incomplete exception logging in AsertoAuthorizationManager

### ISSUE THREAD

**Issue by reardonm** [aserto-dev/aserto-spring#8]
The `AsertoAuthorizationManager` class catches and logs exceptions but only logs the exception message, losing the root cause. This can make troubleshooting misconfigurations and other problems difficult, as the root cause of the exception may be lost.
Example:
```java
try {
    List<Decision> decisions = authzClient.is(identityCtx, policyCtx, resourceCtx);
    isAllowed = isAllowed(decisions);
} catch (Exception e) {
    log.error("Is call failed [{}]",  e.getMessage());
    return new AuthorizationDecision(false);
}
```
Suggested Solution:

Change the logging statement to log the full exception chain:
```java
log.error("Is call failed",  e);
```

**Comment by ogazitt** [comment]
Thanks @reardonm!  We are reviewing this now.

**Comment by gertd** [comment]
Added in aserto-spring v0.2.2

https://central.sonatype.com/artifact/com.aserto/aserto-spring
https://github.com/aserto-dev/aserto-spring
